- name: play level varaibles
  hosts: local
  connection: local
  vars:
    COURSE: "Devops with AWS"
    DURATION: "140HRS"
    TRAINER: "sivakumar"
  tasks: 
  -name: print the varaibles
  ansible.builtin.debug:
     msg: "Course is:  {{COURSE}}, Trainer is: {{TRAINER}}"
