- name: Inventory variable
  hosts: local
  connection: local
  vars:
    COURSE: "DevOps with AWS"
    DURATION: "140HRS"
    TRAINER: "SivaKumar"
  tasks:
  - name: print varaibles
    ansible.builtin.debug:
      msg: "Course is : {{COURSE}}"